name: Build Docker Image - MP
on:
  workflow_dispatch: 
  watch:
    types: [started]
  schedule: 
    - cron: 21 23,11 * * *
    - cron: 1 1,13 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image - PUBLIC
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: '${{ secrets.DOCKER_PATH }}'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - uses: actions/checkout@master
      - name: Building Docker Image - TEST
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: '${{ secrets.DOCKER_PATH_TEST }}'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Record and Commit
        uses: actions/checkout@v2
        run: |
     # 更改时区
        sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        git config --global user.email "asiaqa@duck.com"
        git config --global user.name "MP"
        git add .
        git commit -am "new config"
        git push
